name = "myplanningportal-api"
main = "worker-index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "myplanningportal-db"
database_id = "d4ada005-8201-470f-abd4-d8824be192ddE"
